[project]
name = "server"
version = "0.1.0"
description = "Concierge Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fast-flights>=2.2",
    "fastapi[standard]>=0.116.1",
]
